### ISSUE TITLE
win7SP1x86无法打开

### ISSUE THREAD

**Issue by rscnfan** [EvilCult/Video-Downloader#1]
如题，<a href='http://tietuku.com/4c51c994a4586b8e'><img src='http://i11.tietuku.com/4c51c994a4586b8e.png'></a>

**Comment by danangua** [comment]
我也有同样的问题。Win7 SP1 x86

**Comment by EvilCult** [comment]
这。。。。。应该。。。。。是个。。。。64位程序。。。
sorry。。我的错。。。
几位大爷有没有兴趣考虑下64位系统？？（我就是说说。。。。为个软件换系统这事儿我也不干）

**Comment by rscnfan** [comment]
噗，被坑了，求32位的啊
