### ISSUE TITLE
mac版爱奇艺没办法下载。。。

### ISSUE THREAD

**Issue by daile** [EvilCult/Video-Downloader#13]
没办法下载这个链接

http://www.iqiyi.com/dongman/20111116/e4c7d5bb4bb6c2eb.html#vfrm=2-3-0-1

一直显示“分析中“。。。

求求大神解决一下。。。跪谢了

**Comment by daile** [comment]
真心求大大帮忙 爱奇艺的蜡笔小新想收藏很久了 但目前没有一个下载器能够顺利下载的。。。

**Comment by EvilCult** [comment]
嗯。。最近比较忙（当然，这些都是借口，就是懒）。
所以没上来，就没看到。

嗯。。虽然我不能理解你为啥要在爱奇艺下这个动画片（明明可以一个bt搞定的嘛！！！），但是想收集完整的蛋疼的心情我是感同身受的。。

看了下，这是个比较诡异的问题，大概情况分为两种：
1，显示分析中。。。是卡住了？总之，当前版本的app应该是显示出链接，但是下载不了的。
2，下载不了的问题是爱奇艺视频没有分段，只是做了ts切片，然而下完整视频又超过了最大的可下载长度。

我是这么理解的，很绕，但可以解决，然而我不想再去发布各个版本的程序了，留个邮箱，发你个mac版的吧。（大概就这几天之内）

**Comment by daile** [comment]
biglexiongxiong@163.com

大好人 感激不尽。。。

**Comment by daile** [comment]
网上的小新资源没有一个能比爱奇艺的更完整更具价值了 所以迫切想收藏 苦于没有能力。。。
