### ISSUE TITLE
视频解析，qiyi的，下载完了，还是不完整啊

### ISSUE THREAD

**Issue by zlzdp** [EvilCult/Video-Downloader#16]
视频解析，qiyi的，下载完了，还是不完整啊

网站原版，48分钟多点，
下载是7段，每段是6分钟，算起来总共是42分钟，
不完整啊。

原视频：
www.iqiyi.com/v_19rrl3434o.html

希望修复，谢谢大神。

**Comment by EvilCult** [comment]
同 #13 
爱奇艺面临重大问题，目前**龟速**重写**全部**代码ing。
