### ISSUE TITLE
能下youku么？我随便试了一个地址下不了啊。

### ISSUE THREAD

**Issue by wgf4242** [EvilCult/Video-Downloader#21]
http://v.youku.com/v_show/id_XOTIxNzM1NzI4.html?from=y1.7-2

粘进去点搜索没反应。

**Comment by EvilCult** [comment]
优酷的链接很奇怪，完全搞不懂，有些会在链接里带“==”，有些不带，暂时，遇到没反应的，如果链接里不带“==”，自行加上试试。比如你随便试的这个链接，换成“http://v.youku.com/v_show/id_XOTIxNzM1NzI4==.html?from=y1.7-2”

这个问题会在下一个版本尝试修复（对于优酷不晓得有没有下个版本）
