### ISSUE TITLE
能下iqiyi么？我随便试了一个地址下不了啊

### ISSUE THREAD

**Issue by wgf4242** [EvilCult/Video-Downloader#24]
百度搜的跑男，进入的iqiyi地址。点搜索，一直处于分析中。
http://www.iqiyi.com/v_19rrls2n4w.html?vfm=2008_aldbd
http://www.iqiyi.com/v_19rrls2n4w.html

用上面哪个链接都是在分析中。

**Comment by EvilCult** [comment]
借这个问题再说明一下。
目前正在重构iqiyi的相关解析方式。
好消息是：目前进度几乎达到：95%
坏消息是：剩下的5%似乎宇宙超级霹雳无敌难搞。
swf知识的遗忘以及系统的问题，导致现在卡住了。
正在努力想办法。。

**Comment by hldh214** [comment]
请问进度如何了

**Comment by bbpp5200** [comment]
qiyi貌似改用新型 cmd5 加密方式 貌似很牛的样子

**Comment by LeoQ** [comment]
虽然我已经解决这个问题 但是问了公司老大 不能分享出来解决方案

**Comment by Chinasat9** [comment]
@LeoQ 要付费？
