### ISSUE TITLE
youku什么时候可以更新

### ISSUE THREAD

**Issue by xielongen** [EvilCult/Video-Downloader#26]
youku什么时候可以更新,我自己也尝试着研究了一下,但因为不太了解这个领域,仍是一头雾水.这个项目你也维护了这么久了,能不能总结下载视频这类任务的最佳实践的工具和方法,让更多的人加入其中

**Comment by EvilCult** [comment]
首先，重点，回答你的疑问：

> **没工具 && 没方法**

这种事情是主要需要的东西只有两种：

> **灵感 && 体力**

灵感就是猜，传递视频信息的url，以及url的参数都是什么，那些可有可无，那些是加密算法得到的，加密算法在哪个文件，整个程序的执行流程是什么。。。等等。。。

体力就是理解＋翻译，找到加密算法，普遍都是混淆的，通过对程序的理解反混淆翻译成正常人类写的东西。在翻译成自己程序所用的语言(本项目是python)。。。等等。

pc站主要核心代码都在flash里，所以要会反编译swf，要知道actionscript
m站主要核心代码在js文件里，要知道javascript

其余零零碎碎的http协议，数学等相关伪造request，cookies，位运算等各需了解一点。。。
(说位运算是因为python的算法跟其他的有些不太一样)

最后，重要的事情说三遍

> **没工具 && 没方法**
> **没工具 && 没方法**
> **没工具 && 没方法**

PS：我当然也希望大家一起来，这东西又不难～大家分别各自关注一个站点对应着更新，就能一直维持下去了。
然而这种事情就是猫和老鼠一般的游戏，对方只要稍微改动一点点，就要分析好久。纯粹的体力。难怪大神都不愿意搞这些呢～
