### ISSUE TITLE
分段视频自动合并 视频自动重命名

### ISSUE THREAD

**Issue by Riajyuu** [EvilCult/Video-Downloader#32]
对于优酷土豆等分段视频希望能自动合并
另外合并后最好能自动重命名为下载视频的标题 比如 火影忍者 第XXX集 XXXX

**Comment by EvilCult** [comment]
自动重命名倒是可以实现，鉴于当前情况，视频真实id获取越来越难，这个倒也是在计划之中。
不过合并。。。。。目前绝对不再考虑的范围之内。
视频相关的东西我就不太了解，并且，首要的问题还是把爱奇艺乐视这些个问题都解决了先。。。。

**Comment by aawwsslll** [comment]
先问问默认的HD的代表的是什么画质？720P？

**Comment by EvilCult** [comment]
@1608637229 
默认的HD 基本代表着最高画质，但是这一块有很大的问题。之前也有朋友反映。还是说明白点比较好，只有三种分辨率会比较模糊。
所以，把目前基本功能高稳定后，会重构一下分辨率相关的功能，每个站点添加独立的config参数。
使用起来应该会简单明了很多。

**Comment by woshichenchuana** [comment]
@EvilCult
可以增加1080p？

**Comment by EvilCult** [comment]
@woshichenchuana 
优酷现在支持1080p，除vip资源外。

**Comment by Riajyuu** [comment]
@EvilCult 有办法解析VIP资源吗 youget也只能解析到前六分钟

**Comment by EvilCult** [comment]
@EMLVIRUS 
有，有个会员账号就行，以测试，可以获取全部资源。

**Comment by wnpllrzodiac** [comment]
视频合并可以联系我，我视频多媒体开发多年

**Comment by zhangxulong** [comment]
视频合并，很简单，ffmpeg就好了，可以去看一下我的GitHub  videotools
