### ISSUE TITLE
想问下这些算法你是怎么知道的呢？

### ISSUE THREAD

**Issue by pqsky** [EvilCult/Video-Downloader#39]
您的算法我可以看懂，但是我想问下这些算法你是怎么知道的呢？或者说你是怎么分析出来的呢，可否指导下

**Comment by EvilCult** [comment]
就是“猜、翻译、学”，看手机版网站，**猜**api地址以及大概的javascript执行流程。然后**翻译**javascript，如果搞不定，就去找其他的看远软件**学学**比如youget
