### ISSUE TITLE
非常棒的软件，能增加导出为M3U文件吗？

### ISSUE THREAD

**Issue by shot127** [EvilCult/Video-Downloader#4]
非常棒的作品，直接解析地址用本地播放器观看，还可以硬解。
老机在线看高清视频非常痛苦，这下基本告别卡顿的flash了。
之前用硕鼠，但对A站支持的不太好。用你的软件解析的是不分段的原画画质的A站源，硕鼠解析的确是分段的优酷源。
对于分段视频，能否支持导出为M3U文件，这样就可以连续播放了。
非常感谢感谢！

**Comment by EvilCult** [comment]
这个倒是可以，也是非常简单，毕竟在得到m3u8文件之后才能得到视频真实地址的（一部分是这样，不过另一部份可能需要有所改动）。
但是如果你只是单纯的想要观看视频并且抛弃flash的话。。。。。。
哈哈哈哈哈哈
plz百度搜索如下字段：“妈妈再也不用担心我的macbook发烫了”
那个才是真正的棒的作品，我也一直在用哦。
帮神器打个广告。
（毕竟本作主要还是搜藏癖下载～～_^___^_）

**Comment by shot127** [comment]
以前用过mama2，支持的网站比较少，就没有用下去。现在支持acfun和bilibili了，太棒了！
感谢推荐！
期待新版本的Video-Downloader

在 2016年2月15日 下午12:35，Ray H. notifications@github.com写道：

**Comment by EvilCult** [comment]
不必客气，能帮到你就好！
