### ISSUE TITLE
B站番剧解析

### ISSUE THREAD

**Issue by Riajyuu** [EvilCult/Video-Downloader#40]
无法解析位于bangumi.bilibili.com/*下的番剧合集

**Comment by EvilCult** [comment]
bangumi.bilibili.com
呐尼？？这是啥？？？？
这东西我都不知道，肯定不在分析的范围内。。。。
没看过呢。。。有时间我看看。。。
= =#

**Comment by Riajyuu** [comment]
随便找一个B站番剧合集就行
比如这个月的新番三年E班Q （也就是暗杀教室第三季）
以第一集为例 http://bangumi.bilibili.com/anime/5830/play#98483
you-get 解析结果为 
![image](https://cloud.githubusercontent.com/assets/16912240/21920951/6aa7bbd0-d99f-11e6-9fab-de499acf14c2.png)
