### ISSUE TITLE
命令行版？

### ISSUE THREAD

**Issue by yellowlm** [EvilCult/Video-Downloader#41]
同学有命令行版么~~~？

**Comment by EvilCult** [comment]
老师，这个真真不会弄。

**Comment by Kugel-Blitz** [comment]
。。。要不要从you-get和youtube-dl哪里偷一点来？
不需要什么很复杂的选择清晰度的功能。。。只求能批处理。。。（准备从优酷上把柯南下下来，然后you-get实在不稳定。。。要么就是macOS有毒，该回归windows了。。。）
