### ISSUE TITLE
Mac版本有时候不能粘贴地址？

### ISSUE THREAD

**Issue by Kugel-Blitz** [EvilCult/Video-Downloader#43]
Mac版有50%的几率抽风，然后地址无法粘贴。。。手动输入多么蛋疼还望理解。。。

**Comment by EvilCult** [comment]
我可以理解。。。。
GUI图形界面采用的是Tkinter。。。。
这个问题，很可能是电脑的问题。。。一些个配置之类的。。。
或者，Tkinter这个东西本来就很low。。。出了问题也不奇怪。。。
关键是还丑！！！
我倒是很有兴趣换一个GUI界面框架。。。。
但考虑到学习成本。。。。所以这个问题只能以后再解决了。。。

**Comment by Kugel-Blitz** [comment]
其实弄个命令行也可以。。。然后就是希望可以导入cookies（是不是要求太高了）
