### ISSUE TITLE
youku是否失效了?

### ISSUE THREAD

**Issue by kof11** [EvilCult/Video-Downloader#44]
解析不完整，下載下來的視頻全都無法正常觀看
http://v.youku.com/v_show/id_XMjUwMzczMDk2NA==.html

**Comment by EvilCult** [comment]
是最新版本？按照我瞎写的版本现在最新的应该是0.9.4.。。。
我试了下还是好使的。。。可以下高清，就是指优酷的“超清”。
现在hd指1080p。。。看来分析还是有点问题的。。。。。

**Comment by novicewu** [comment]
youku好像不行了。找不到视频。帮忙看看怎么回事
http://v.youku.com/v_show/id_XNzgwNDc2OTc2.html

<img width="671" alt="screen shot 2017-02-19 at 21 02 44" src="https://cloud.githubusercontent.com/assets/8786994/23102594/cb174260-f6e6-11e6-81d6-d925fcf6f27d.png">
