### ISSUE TITLE
有办法和兴趣支持爱奇艺会员1080P解析吗？

### ISSUE THREAD

**Issue by BreakshadowCN** [EvilCult/Video-Downloader#46]
抱歉提了这么个天马行空的Feature Request，但是我太想下载某个演唱会的视频了，但它却是在爱奇艺会员独享的列表里，非会员清晰度最高720P，而我是那么想下载这个1080P。
视频链接：http://www.iqiyi.com/v_19rr9db7u4.html

**Comment by EvilCult** [comment]
不用抱歉。。。你的愿望应该被满足。。。。
https://pan.baidu.com/s/1o8bcP8Q
直接去拿迅雷下。。。反正我试了，可以下。。。。
何必一条路走到到黑。。。

**Comment by BreakshadowCN** [comment]
@EvilCult 十分感谢，然而我是想下载目前爱奇艺里边这一版的。。
虽然画质差，自带官方字幕，摄影机机位也不一样的。。。
无论如何，谢谢了。
