### ISSUE TITLE
关于GPL协议的疑问...

### ISSUE THREAD

**Issue by Kagamia** [EvilCult/Video-Downloader#47]
试着把部分代码用C#重新实现了一遍（基本是py的行级重写）
请问我需要将这份代码开源并且强制遵守GPL协议吗？

因为没有遇到对应的场合故诚心询问_(:з)∠)_
如果是肯定答复的话求详细解释_(:з)∠)_ 有参考资料是极好的_(:з)∠)_

**Comment by EvilCult** [comment]
如果是行级重写，那答案是肯定的，你要开源的。

详细解释：
如果你仅更换了开发语言，但逻辑思路等与原来完全相同。那你这个软件仍属于我的软件的GPL衍生品，也会受到限制必须持续开源。
但有例外则是，GPL是发行协议，如果你仅仅是自用闭源，就无所谓了。

但实际中，这种对GPL软件的修改，比较难以界定，如果直接使用了GPL的开源库，肯定是要遵守的，但是软件的其他逻辑部分。。。比较难说，你懂的。如果我是腾讯有钱有人，你就死定了。。。

不过有个好消息告诉你，我是个完全不在意这些的人，GPL协议也是我随意加的。
你可以随意拿去进行封装or直接用，拿python进行行级重写我都不介意。

以上的言论可以当做我对你的“授权”。。。。。

**Comment by Kagamia** [comment]
感谢回复 😆 
为了谨慎起见已经开源并遵守GPL协议~ [→在这里](https://github.com/Kagamia/VideoDownloader)
大概后续会移植更多代码过去>.<
