### ISSUE TITLE
支持命令行吗

### ISSUE THREAD

**Issue by hnwy** [EvilCult/Video-Downloader#6]
由于主力机是chromebook，没有安装crouton，不能运行Linux X软件，纯命令行的可以

**Comment by EvilCult** [comment]
命令行的的程序。。。。我就不太会。。。
不过命令行执行这些个功能，倒是能去先做到。
去掉GUI模块，CD进入文件夹执行一个py文件。而且前提是需要pycurl支持。
这样你能接受么～囧rz

**Comment by hnwy** [comment]
我觉得，我刷crouton靠谱点[微笑]
