### ISSUE TITLE
电影无法下全（可能还包括其他长视频）

### ISSUE THREAD

**Issue by ShadyZOZ** [EvilCult/Video-Downloader#9]
下载电影的时候只能下载一半，测试电影：

> http://v.youku.com/v_show/id_XMTQwMTc4ODAyNA==.html
> http://v.youku.com/v_show/id_XMTM4OTE5Mjc2OA==.html

两部都只下载了50多分分钟，段落解析不完整，不知问题出在哪里。

测试过一部65分钟的视频（非电影）可以完整下载到。

**Comment by EvilCult** [comment]
已经发现了，优酷貌似更新了个什么机制，对于一些电影，综艺节目之类的，**所有**使用优酷**移动端**结构获取视频的方式，都只能得到50分钟长度的视频，包括优酷自己的手机站，怎么样，优酷垃圾吧。所以整个优酷的解析要从头再来，预计要在下下下次更新中修正。
